### ISSUE TITLE
Auto-Shuttle gets called but never shows up!

### ISSUE THREAD

**Issue by 0xRainy** [MOONMOONOSS/tgstation#29]
## Reproduction: 3-4 People on, all but one die. Shuttle gets called automatically, but never shows up. We were in lavaland, but it has also happened when on station.

No Var edits this round.

**Comment by Kexerval** [comment]
http://ss13.moontaku.com/logs/round-149.zip

**Comment by Kexerval** [comment]
Found potential runtime warning relevant to this issue: 
File: `runtime.log`
Line: `166`
`[2019-09-23 18:54:26.042] ## WARNING: couldn't find shuttle with id: pod1 in code/controllers/subsystem/shuttle.dm at line 166 src: Shuttle usr: Kamahl Sparks.`

**Comment by Kexerval** [comment]
@0xRainy Potential fix in 266efd614f3760cc4011b550e1610d2d5800bf0d

**Comment by Kexerval** [comment]
Fixed in 266efd6
